select
  coalesce(cast(snapshot_date as date), current_date()) as snapshot_date,
  'rent' as mode,
  source,
  source_listing_id,
  source_url,
  title,
  description,
  cast(price_total as float64) as price_total,
  currency,
  cast(area_sqm as float64) as area_sqm,
  cast(rooms as float64) as rooms,
  floor,
  seller_segment,
  seller_type,
  city,
  municipality,
  district,
  cast(price_per_sqm as float64) as price_per_sqm,
  building_type,
  market_type,
  furnished,
  elevator,
  pets_allowed,
  room_type,
  parking,
  preferred_tenants,
  building_floors,
  cast(land_area_sqm as float64) as land_area_sqm,
  cast(price_per_sqm_source as float64) as price_per_sqm_source,
  detail_params,
  detail_params_common,
  detail_params_rent
from {{ source('bronze', 'olx_rent_all') }}
where source = 'olx'
