from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Callable
from pathlib import Path
from typing import Any

from domus_dweller.sources.olx.parser import parse_search_results as parse_olx_search_results
from domus_dweller.sources.otodom.parser import parse_search_results as parse_otodom_search_results

PARSERS: dict[str, Callable[[str], list[dict[str, Any]]]] = {
    "otodom": parse_otodom_search_results,
    "olx": parse_olx_search_results,
}


def _build_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Parse saved search-results HTML for a source.")
    parser.add_argument("--source", choices=sorted(PARSERS), required=True)
    parser.add_argument(
        "--input",
        type=Path,
        required=True,
        help="Path to source HTML fixture/file.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Optional output JSON file path. Prints to stdout when omitted.",
    )
    parser.add_argument(
        "--fail-on-block",
        action="store_true",
        help="Exit with non-zero status when source response is a known block page.",
    )
    return parser.parse_args()


def main() -> None:
    args = _build_args()
    raw_html = args.input.read_text(encoding="utf-8")
    if args.source == "otodom" and _is_cloudfront_block_page(raw_html):
        print(
            "Warning: Otodom response looks blocked by CloudFront (HTTP 403 challenge page).",
            file=sys.stderr,
        )
        if args.fail_on_block:
            raise SystemExit(2)
    listings = PARSERS[args.source](raw_html)

    payload = json.dumps(listings, ensure_ascii=False, indent=2)
    if args.output is None:
        print(payload)
        return

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(payload + "\n", encoding="utf-8")
    print(f"Wrote {len(listings)} parsed listings to {args.output}")


def _is_cloudfront_block_page(raw_html: str) -> bool:
    return "403 ERROR" in raw_html and "Generated by cloudfront" in raw_html


if __name__ == "__main__":
    main()
