import json
from pathlib import Path

import pytest
from domus_dweller import parse


def test_given_otodom_fixture_when_running_cli_then_json_is_printed(
    monkeypatch,
    capsys,
) -> None:
    # Given
    fixture = Path("ingestion/tests/fixtures/otodom/search_results.html")
    monkeypatch.setattr(
        "sys.argv",
        [
            "parse",
            "--source",
            "otodom",
            "--input",
            str(fixture),
        ],
    )

    # When
    parse.main()

    # Then
    stdout = capsys.readouterr().out
    parsed = json.loads(stdout)
    assert parsed[0]["source"] == "otodom"
    assert parsed[0]["source_listing_id"] == "otodom-12345"


def test_given_output_path_when_running_cli_then_file_is_written(
    monkeypatch,
    tmp_path,
    capsys,
) -> None:
    # Given
    fixture = Path("ingestion/tests/fixtures/olx/search_results.html")
    output_path = tmp_path / "parsed" / "olx.json"
    monkeypatch.setattr(
        "sys.argv",
        [
            "parse",
            "--source",
            "olx",
            "--input",
            str(fixture),
            "--output",
            str(output_path),
        ],
    )

    # When
    parse.main()

    # Then
    stdout = capsys.readouterr().out
    assert "Wrote 1 parsed listings" in stdout
    parsed = json.loads(output_path.read_text(encoding="utf-8"))
    assert parsed[0]["source"] == "olx"
    assert parsed[0]["seller_segment"] == "private"


def test_given_otodom_block_page_and_fail_flag_when_running_cli_then_exit_non_zero(
    monkeypatch,
    tmp_path,
) -> None:
    # Given
    blocked_html = tmp_path / "blocked.html"
    blocked_html.write_text(
        "<html><body><h1>403 ERROR</h1><pre>Generated by cloudfront</pre></body></html>",
        encoding="utf-8",
    )
    monkeypatch.setattr(
        "sys.argv",
        [
            "parse",
            "--source",
            "otodom",
            "--fail-on-block",
            "--input",
            str(blocked_html),
        ],
    )

    # When / Then
    with pytest.raises(SystemExit) as exc:
        parse.main()
    assert exc.value.code == 2
